### PR TITLE
[] add templated circleci config

### PR DESCRIPTION
**Pull request by fugufisch**
This config will be added if you choose to create the infra for the prediction container.

### CODE REVIEW

**Review by CamposContentful — COMMENTED** [review]
I was thinking about adding some mypy, pytest and tox checks in the CI.
But I'm confused about how to integrate them with this file.
Can we have optional CI jobs as independent files?

**Comment by fugufisch** [comment]
I don't know if different files, but they could be added as separate optional workflow jobs.

**Comment by CamposContentful** [comment]
For sure, but here the creation of the file is dependent on the option, right?
Ideally, it would have a base file and this would be the optional job.

**Comment by fugufisch** [comment]
Oh yeah. As soon as we have a base config we can do that.

**Comment by CamposContentful** [comment]
> 

That would mean having a separate PR to add the base CI config and then fixing this PR  to append this config as a separated job, right?

**Review by CamposContentful — APPROVED** [review]

**Pull request merged**
